new_feature_request:
  description: >
    New feature request.
    Users have a new feature they would like to implement in {project_name}.
    Prompt the users to provide a brief description of the feature, then come up with an implement plan.
    It is imperative that you gather the details by asking questions to the human users.
    Create a ticket in JIRA to track the work, fill it with all the details
    and assign it to the backend developer.
    If you need help for the design, reach out to the users for architectural
    questions and decisions
  expected_output: >
    A fully specified JIRA ticket with all the details of the new feature,
    including a description, acceptance criteria, and any relevant information.
    The ticket should be assigned to the backend developer.
  agent: business_analyst

new_feature_implementation:
  description: >
    New feature implementation. Once the business analyst has created a JIRA ticket
    for the new feature, the backend developer should implement it.
    Use the information from the JIRA ticket to implement the new feature.
    Add the implementation details to the ticket and update the status.
    Make sure to add unit tests to cover the acceptance criteria mentioned in the ticket.
    Once the feature is implemented, reach out to the users to get their feedback
    and make any necessary adjustments.
  expected_output: >
    A new branch in the repository with the implementation of the new feature,
    including unit tests that cover the acceptance criteria mentioned in the ticket.
    The JIRA ticket should be updated with the implementation details and the status.
  agent: backend_developer
